USE ROLE ACCOUNTADMIN;
CREATE ROLE test_role;

CREATE DATABASE IF NOT EXISTS SNOWPARK_DEFINITIVE_GUIDE;
GRANT OWNERSHIP ON DATABASE SNOWPARK_DEFINITIVE_GUIDE TO ROLE test_role COPY CURRENT GRANTS;
CREATE OR REPLACE WAREHOUSE COMPUTE_WH WITH
  WAREHOUSE_SIZE='X-SMALL';
GRANT USAGE ON WAREHOUSE COMPUTE_WH TO ROLE test_role;

CREATE SECURITY INTEGRATION IF NOT EXISTS snowservices_ingress_oauth
  TYPE=oauth
  OAUTH_CLIENT=snowservices_ingress
  ENABLED=true;

GRANT BIND SERVICE ENDPOINT ON ACCOUNT TO ROLE test_role;

CREATE COMPUTE POOL snowpark_cs_compute_pool
  MIN_NODES = 1
  MAX_NODES = 1
  INSTANCE_FAMILY = CPU_X64_XS;
GRANT USAGE, MONITOR ON COMPUTE POOL snowpark_cs_compute_pool TO ROLE test_role;


GRANT ROLE test_role TO USER [user_name];


USE ROLE test_role;
USE DATABASE SNOWPARK_DEFINITIVE_GUIDE;
USE WAREHOUSE COMPUTE_WH;

CREATE SCHEMA IF NOT EXISTS MY_SCHEMA;
CREATE IMAGE REPOSITORY IF NOT EXISTS snowpark_cs_repository;
CREATE STAGE IF NOT EXISTS snowpark_cs_stage
  DIRECTORY = ( ENABLE = true );


SHOW COMPUTE POOLS;
SHOW WAREHOUSES;
SHOW IMAGE REPOSITORIES;
SHOW STAGES;
